### ISSUE TITLE
Unknown profile?

### ISSUE THREAD

**Issue by razvanphp** [ibc/h264-profile-level-id#2]
First of all, thank you for this lib, it's really useful for our project.

We have a question and improvement proposal:
We use the `RTCRtpReceiver.getCapabilities('video').codecs` in Chrome to detect the browser profiles and we also get this line:
```
90000  | video/H264 | level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=f4001f
```

It seems that this profile is custom/unknown, `parseProfileLevelId('f4001f')` returns `null`, any idea where it might come from?

**Comment by ibc** [comment]
Fixed in https://github.com/ibc/h264-profile-level-id/commit/506c02a51e15dc43366829878891c7b75345a6bd.

I'm releasing new versions of mediasoup and mediasoup-client wiht the new version.

**Comment by ibc** [comment]
h264-profile-level-id 1.1.0 released.

**Comment by razvanphp** [comment]
Thank you for the quick fix! We should probably add tests for this, but will come back with a MR including also some TS fixes 🙂

**Comment by ibc** [comment]
There are no tests for the new profile in libwebrtc and I don't really know how it should be tested. Please add tests in a PR if you know.

**Comment by razvanphp** [comment]
Ah, I meant that we just test the return value of the example in the OP, since it's used in Chrome already.

**Comment by ibc** [comment]
I don't know which profile and level that new value must return. If you know then don't hesitate to add a new test line in test.js.

**Comment by razvanphp** [comment]
Isn't it profile `PredictiveHigh444` and level `3.1`? Or am I missing something?

**Comment by ibc** [comment]
I know absolutely nothing about these values and this library. I just ported it from C++ to JS. I cannot help with how it should behave for new profile values.

**Comment by ibc** [comment]
> but will come back with a MR including also some TS fixes

mmm, I've done this: https://github.com/ibc/h264-profile-level-id/pull/5
