### ISSUE TITLE
Convenience toHumanReadable() method

### ISSUE THREAD

**Issue by razvanphp** [ibc/h264-profile-level-id#3]
Can we contribute with a method we use in our project that decodes the ProfileLevelId into a human readable format like `High@L4.2`, `Profile: High, Level: 4.2`  or similar? `Profile: 5` is still hard to guess, maybe we could use a more general constant value like the int value:
```
Baseline (66)
Main (77)
Extended (88)
High (100)
```

Currently to do this with your lib, one needs to add all the constants to the code and keep them updated/in sync in case they ever get modified.

Thank you!
R

**Comment by ibc** [comment]
Version 1.1.1 comes with `profileToString()` and `levelToString()` new exported functions.

**Comment by razvanphp** [comment]
Awesome! Cheers!
